- name: "node"
  description: "Node.js 相关命令"
  template: "node {command}"
  tags: ["nodejs", "runtime"]
  globalParams:
    - param: "output"
      type: "string"
      description: "输出格式"
      default: "json"
      required: false
  subCommands:
    - name: "list"
      description: "列出所有 Node.js 版本"
      template: "list"
      parameters:
        - param: "remote"
          type: "boolean"
          description: "是否显示远程版本"
          default: "true"
          required: false
