- name: "node"
  description: "Node.js 相关命令"
  template: "{command}"
  tags: ["nodejs", "runtime"]
  globalParams:
    - param: "output"
      type: "string"
      description: "输出格式"
      default: "json"
      required: false
  subCommands:
    - name: "list"
      description: "列出所有 Node.js 版本"
      template: "list {remote}"
      parameters:
        - param: "remote"
          type: "boolean"
          description: "是否显示远程版本"
          default: "true"
          required: false

- name: "git"
  description: "Git 相关命令"
  template: "git {command}"
  tags: ["git", "vcs"]
  globalParams:
    - param: "verbose"
      type: "boolean"
      description: "显示详细信息"
      default: "false"
      required: false
  subCommands:
    - name: "commit"
      description: "提交更改"
      template: "commit -m '{message}'"
      parameters:
        - param: "message"
          type: "string"
          description: "提交信息"
          required: true